### PR TITLE
Fix PHP errors

### LINKED ISSUE #146: [Est:1] [Prestashp] Error on PHP log
Hi! Please add needed ifs to prevent this error.
Occurs while sync catalog on prestashop module.

```
Got error 'PHP message: PHP Warning:  array_column() expects parameter 1 to be array, bool given in 
/var/www/vhost/psapp.sdi.es/home/html/modules/doofinder/feeds/product.php on line 533

PHP message: PHP Warning:  array_map(): Expected parameter 2 to be an array, null given in 
/var/www/vhost/psapp.sdi.es/home/html/modules/doofinder/feeds/product.php on line 534

PHP message: PHP Warning:  implode(): Invalid arguments passed in 
/var/www/vhost/psapp.sdi.es/home/html/modules/doofinder/feeds/product.php on line 534'
```

### LINKED ISSUE #201: Problem when adding/updating products on big catalogs
Hi ! 

I faced an issue with the module on some CLI scripts. 
When the function DfCategoryBuild::buildCategory($category) is called with a non valid Category object, this line break the code and exit with an exception : 
image

I just added a fix on the function  DfCategoryBuild::build() to avoid this issue :
 
image

On the foreach, just added this code :
`if (!Category::categoryExists($category)) {
                continue;
            }`
            
            
Have a nice day

### PR DESCRIPTION
**Pull request by yuloma**
Como son cambios pequeños agrupé dos tickets en este PR.

https://github.com/doofinder/doofinder-prestashop/issues/146
https://github.com/doofinder/doofinder-prestashop/issues/201

### CODE REVIEW

File: src/Entity/DfCategoryBuild.php [hunk 1]
```diff
@@ -47,7 +47,9 @@ public function build($json = true)
         $this->assign();
 
         foreach ($this->categories as $category) {
-            $payload[] = $this->buildCategory($category);
+            if (\Category::categoryExists($category)) {
+                $payload[] = $this->buildCategory($category);
+            }
```
Comment (davidmolinacano) [inline src/Entity/DfCategoryBuild.php:52]: Another way (but your code is excellent too, just to comment it). Guard clause way:

```suggestion
            if (!\Category::categoryExists($category)) {
                continue;
            }
            $payload[] = $this->buildCategory($category);
```

**Review by davidmolinacano — APPROVED** [review]
LGTM! Great!! :trophy:

**Review by ogomezba — APPROVED** [review]

File: src/Entity/DfCategoryBuild.php (hunk 1 above)
Comment (yuloma) [reply src/Entity/DfCategoryBuild.php:52]: great!
