### PR TITLE
Fix autoloader

### LINKED ISSUE #353: [Prestashop] Autoload
Mejorar la organización de los ficheros del plugin para utilizar el autoload

### PR DESCRIPTION
**Pull request by mursisoy**
With this PR we are able to reorganize the files under `src` under their correct namespace and not everything under `src/Entity`.

When adding new classes we should run `make dump-autoload` to update the files generated.

### CODE REVIEW

**Comment by mursisoy** [comment]
I got some mixed feeling uploading the vendor module as is. Maybe is it better to generate the autoload files and move them to the root or other directory to not break composer? Because I am not very convinced with this `vendor` thing I am going to make a move.

**Comment by mursisoy** [comment]
> I got some mixed feeling uploading the vendor module as is. Maybe is it better to generate the autoload files and move them to the root or other directory to not break composer? Because I am not very convinced with this `vendor` thing I am going to make a move.

I say nothing: https://devdocs.prestashop-project.org/8/modules/concepts/composer/

image

**Comment by mursisoy** [comment]
So, maybe I just need to run it locally and in the action to package the release with all the dependencies.

File: src/Entity/DoofinderConstants.php [hunk 1]
```diff
@@ -22,7 +22,7 @@
 class DoofinderConstants
 {
     // Feel free to change this value to your own local env or ngrok
-    const ENV = 'prod'; // Useful to set eu1 as the default region in the Autoinstaller if the value is different than 'prod'
+    const ENV = 'dev'; // Useful to set eu1 as the default region in the Autoinstaller if the value is different than 'prod'
```
Comment (sofia-doofinder) [inline src/Entity/DoofinderConstants.php]: este cambio es seguro? por defecto no debería ser `prod`?

File: vendor/composer/autoload_classmap.php [hunk 2]
```diff
@@ -0,0 +1,35 @@
+<?php
+
+// autoload_classmap.php @generated by Composer
+
+$vendorDir = dirname(dirname(__FILE__));
+$baseDir = dirname($vendorDir);
+
+return array(
```
Comment (sofia-doofinder) [inline vendor/composer/autoload_classmap.php:8]: cada vez que se cree una nueva clase hay que meterlo aquí? o aquí se meteran automáticamente usando el `make dump-autoload`?

File: .env [hunk 3]
```diff
@@ -4,13 +4,19 @@ MYSQL_USER=prestashop
 MYSQL_PASSWORD=prestashop
 
 #PS Versions to use
-PS_VERSION=1.7.8.9
-PHP_VERSION=7.4
+PS_VERSION=1.6
+PHP_VERSION=5.6
```
Comment (sofia-doofinder) [inline .env]: mejor dejar como "por defecto" alguna mas moderna no?

**Review by sofia-doofinder — CHANGES_REQUESTED** [review]
Algunas dudas Alberto

**Review by davidmolinacano — CHANGES_REQUESTED** [review]
I would suggest to test it carefully just in case, because the last time I uploaded the vendor in the final ZIP I wasn't able to install it after uploading the ZIP to the module manager.

File: src/Entity/DoofinderConstants.php (hunk 1 above)
Comment (davidmolinacano) [reply src/Entity/DoofinderConstants.php]: Coincido con @sofia-doofinder , esto podría haber sido subido por error :sweat_smile:

Comment (pedromcp90) [reply src/Entity/DoofinderConstants.php]: +1

File: .env (hunk 3 above)
Comment (pedromcp90) [reply .env]: Estoy de acuerdo con @sofia-doofinder, deberíamos mantener las versiones por defecto que teníamos.

**Review by pedromcp90 — CHANGES_REQUESTED** [review]
Tiene buena pinta, solo revisa algunos comentarios que hemos dejado y confirma que al generar el zip la instalación funciona correctamente.

File: src/Entity/DoofinderConstants.php (hunk 1 above)
Comment (mursisoy) [reply src/Entity/DoofinderConstants.php]: Mistake, sry

File: vendor/composer/autoload_classmap.php (hunk 2 above)
Comment (mursisoy) [reply vendor/composer/autoload_classmap.php:8]: El `make dump-autoload` se encarga de todo. Lo que habría que poner la ejecución en el flujo de init y/o start.

File: .env (hunk 3 above)
Comment (mursisoy) [reply .env]: Resuelto.

**Review by sofia-doofinder — APPROVED** [review]

File: vendor/composer/autoload_classmap.php [hunk 4]
```diff
@@ -0,0 +1,37 @@
+<?php
```
Comment (davidmolinacano) [inline vendor/composer/autoload_classmap.php:1]: I have to confess that this is the first time I see a vendor being included on Git, but this way it should work :thinking:

**Review by davidmolinacano — APPROVED** [review]

File: upgrade/upgrade-4.2.0.php [hunk 5]
```diff
@@ -23,6 +23,7 @@
  * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
  * International Registered Trademark & Property of PrestaShop SA
  */
+
```
Comment (davidmolinacano) [inline upgrade/upgrade-4.2.0.php]: Be careful, because this empty lines seems to fail in the validator:

image

https://validator.prestashop.com/module/3625699/validate

**Review by davidmolinacano — CHANGES_REQUESTED** [review]

File: vendor/composer/autoload_classmap.php (hunk 4 above)
Comment (mursisoy) [reply vendor/composer/autoload_classmap.php:1]: They package that way. The other options is to generate on the fly when creating the release :/

File: upgrade/upgrade-4.2.0.php (hunk 5 above)
Comment (mursisoy) [reply upgrade/upgrade-4.2.0.php]: Damn, I put them cause I think they where better :/

File: vendor/composer/autoload_classmap.php (hunk 4 above)
Comment (mursisoy) [reply vendor/composer/autoload_classmap.php:1]: > > I got some mixed feeling uploading the vendor module as is. Maybe is it better to generate the autoload files and move them to the root or other directory to not break composer? Because I am not very convinced with this `vendor` thing I am going to make a move.
> 
> I say nothing: https://devdocs.prestashop-project.org/8/modules/concepts/composer/
> 
> image

They suggest doing that, prior to release, but.... I don't know

**Review by davidmolinacano — APPROVED** [review]

**Review by sofia-doofinder — APPROVED** [review]
:ok_hand:

**Review by pedromcp90 — APPROVED** [review]
